### ISSUE TITLE
Interpretation of documents without a subtitle fails

### ISSUE THREAD

**Issue by PetrilloAtWork** [slaclab/slac-beamer-template#1]
When removing the subtitle line in `exampleSLAC.tex`, I get the following error:
    
    ! LaTeX Error: Something's wrong--perhaps a missing \item.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                  
    l.3 \item
          This is an \underline{inofficial} \LaTeX-beamer template for SLAC.

Rendered with `latexmk -pdf exampleSLAC.tex`.
The subtitle _should_ be optional.

-------------------------------

Using TeXLive 2019 under OpenSUSE Linux.

**Comment by skuschel** [comment]
Thanks for spotting this! I hope the change helps on your system. I tested with `pdflatex exampleSLAC.tex` on arch linux.
